"
Relative right hand rotation of Je wrt Ie.
zIe must be parallel or nearly so to zJe.
thez can be finite.
thex and they must be small - say less than 10 degrees.
"
Class {
	#name : #MbDAngleIeJe,
	#superclass : #MbDKinematicIeJe,
	#category : #'StCAD-MbD-MbDKinematicIJ'
}

{ #category : #'VisualWorks metadata' }
MbDAngleIeJe class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]
