Class {
	#name : #MbDReactionMag,
	#superclass : #MbDReaction,
	#category : #'StCAD-MbD-MbDReaction'
}

{ #category : #'VisualWorks metadata' }
MbDReactionMag class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.MbD'
	)

]

{ #category : #accessing }
MbDReactionMag >> partFrameK [
	^nil
]

{ #category : #accessing }
MbDReactionMag >> pvaluepEK [
	^nil
]

{ #category : #accessing }
MbDReactionMag >> pvaluepXK [
	^nil
]
