Class {
	#name : #Extrapolator,
	#superclass : #DifferenceOperator,
	#category : #'StCAD-Math-StMathDifferenceOperator'
}

{ #category : #calc }
Extrapolator >> formTaylorMatrix [
	"
	For method order 3: 
	|	1	(t1 - t)	(t1 - t)^2/2!		(t1 - t)^3/3!	|	|q(t)	|	=	|q(t1)	| 
	|	1	(t2 - t)	(t2 - t)^2/2!		(t2 - t)^3/3!	|	|qd(t)	|		|q(t2)	| 
	|	1	(t3 - t)	(t3 - t)^2/2!		(t3 - t)^3/3!	|	|qdd(t)	|		|q(t3)	| 
	|	1	(t4 - t)	(t4 - t)^2/2!		(t4 - t)^3/3!	|	|qddd(t)|		|q(t4)	| 
	"

	self instanciateTaylorMatrix.
	1 to: order + 1 do: [:i | self
			formTaylorRow: i
			withTimeNode: i
			derivative: 0]
]
