Class {
	#name : #MbDSolver,
	#superclass : #Object,
	#category : #'StCAD-MbD-MbDSolver'
}

{ #category : #'instance creation' }
MbDSolver class >> new [
	^super new initialize
]

{ #category : #'VisualWorks metadata' }
MbDSolver class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
	)

]

{ #category : #'initialize-release' }
MbDSolver >> initialize [
]

{ #category : #'initialize-release' }
MbDSolver >> initializeGlobally [
]

{ #category : #'initialize-release' }
MbDSolver >> initializeLocally [
]
