Class {
	#name : #MbDTime,
	#superclass : #MathTime,
	#category : #'StCAD-MbD-MbDBasic'
}

{ #category : #'VisualWorks metadata' }
MbDTime class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.MbD'
		'superclassNamespace' 'StCAD.Math'
	)

]

{ #category : #accessing }
MbDTime >> fillJointForces: orderedCollection [ 
	"Do nothing."
]

{ #category : #accessing }
MbDTime >> fillJointTorques: orderedCollection [ 
	"Do nothing."
]

{ #category : #accessing }
MbDTime >> fillKineIJs: orderedCollection [ 
	"Do nothing."
]

{ #category : #accessing }
MbDTime >> fillKinedotIJs: orderedCollection [ 
	"Do nothing."
]
