Class {
	#name : #Frame,
	#superclass : #GEOMarker,
	#category : #'StCAD-Geo-Geo'
}

{ #category : #'VisualWorks metadata' }
Frame class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.UI.PDMS'
		'superclassNamespace' 'StCAD.Geo'
	)

]

{ #category : #'VisualWorks metadata' }
Frame class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.UI.MOSES'
		'superclassNamespace' 'StCAD.Geo'
	)

]

{ #category : #'VisualWorks metadata' }
Frame class >> visualWorksMetadata [

	^ #(
		'namespace' 'StCAD.UI.POVRay'
		'superclassNamespace' 'StCAD.Geo'
	)

]
